[package]
name = "esctl"
version = "0.1.0"
edition = "2021"
description = "A full-featured Elasticsearch CLI written in Rust"

[[bin]]
name = "esctl"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.4.18", features = ["derive", "env", "string"] }
tokio = { version = "=1.35.1", features = ["full"] }
reqwest = { version = "=0.11.18", default-features = false, features = ["rustls-tls", "json", "stream"] }
serde = { version = "=1.0.193", features = ["derive"] }
serde_json = { version = "=1.0.108" }
toml = "=0.5.11"
comfy-table = "=7.0.1"
colored = "=2.0.4"
colored_json = "=3.2.0"
indicatif = "=0.17.6"
is-terminal = "=0.4.9"
anyhow = "=1.0.75"
thiserror = "=1.0.51"
dirs = "=5.0.1"
url = "=2.4.1"
idna = "=0.4.0"
h2 = "=0.3.24"
indexmap = "=1.9.3"

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "=2.3.2", default-features = false, features = ["linux-keyutils"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
keyring = "=2.3.2"
